### ISSUE TITLE
Deploy module to the Powershell Gallery

### ISSUE THREAD

**Issue by sqlwhale** [sqlwhale/PSRedgate#8]
I think we have the base level functionality. U think we are ready to publish the module. I have to figure out how to get the build to automatically sign the code

**Comment by CollinChaffin** [comment]
If you could possibly either deploy or at the very least update the front page readme that for a very long time has erroneously indicated the install process is to use the gallery, which of course results in error because as of 02-10-2018, it has still not been published.

**Comment by sqlwhale** [comment]
@CollinChaffin I'm finally in a place that I can pick this back up. I'm working on getting this deployed this weekend. Have you had a chance to use it as is?

**Comment by CollinChaffin** [comment]
I wanted to but got tied up lately but it's great to hear you're going to get it published to the gallery!  Ping this thread before you close it if you wouldn't mind to let me know once you have and I'll be one of the first to install via gallery for you!

**Comment by sqlwhale** [comment]
@CollinChaffin I'm happy to say I was finally able to get it to deploy! Let me know what you guys think, it's still in pre 1.0 so I'm sure it needs some more love but honestly this is just a sanitized version of an internal module I've been using for close to 5 years! So I know it works. Especially the backup and restore logic.
